### ISSUE TITLE
Relevance aggregation for Time series forecasting

### ISSUE THREAD

**Issue by ihiratanveer** [sbcblab/RelAgg#2]
Hi, 
Thanks for the well explained implementations. From my understanding, you have applied LRP to classification task.. I want to apply LRP to LSTM for a multivariate time series forecasting task (to predict future values for multiple consecutive days). Will this LRP implementation support the forecasting tasks when the data is tabular?

**Comment by BrunoGrisci** [comment]
> Hi, Thanks for the well explained implementations. From my understanding, you have applied LRP to classification task.. I want to apply LRP to LSTM for a multivariate time series forecasting task (to predict future values for multiple consecutive days). Will this LRP implementation support the forecasting tasks when the data is tabular?

Hi, this current implementation of relevance aggregation does not support LSTM, but it should be straightforward to implement. For reference you may want to read the following references:

https://aclanthology.org/W17-5221.pdf

https://ieeexplore.ieee.org/document/8419358
